name: ci
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # Job name is Greeting
    name: build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: corepack enable
      - run: yarn install --immutable
      - name: Build
        run: yarn run build
      - name: Run linter
        run: yarn run lint